### ISSUE TITLE
Cannot export Pages

### ISSUE THREAD

**Issue by juhanihaapala** [magespecialist/m2-MSP_CmsImportExport#11]
When trying to import single or multiple pages I get the falta erro below with Magento 2.2.6.

`PHP Fatal error:  Uncaught Error: Cannot instantiate interface MSP\\CmsImportExport\\Api\\ContentInterface in /magentoroot/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:111
Stack trace:
#0 /magentoroot/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('MSP\\\\CmsImportEx...', Array)
#1 /magentoroot/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('MSP\\\\CmsImportEx...')
#2 /magentoroot/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\\Framework\\ObjectManager\\Factory\\Compiled->get('MSP\\\\CmsImportEx...')
#3 /magentoroot/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Compiled->create('MSP\\\\CmsImportEx...', Array)
#4 /data/sites/dynamic/aut...`

**Comment by daniloargentiero** [comment]
Fixed in 1.1.0
