### ISSUE TITLE
error while importing

### ISSUE THREAD

**Issue by maxnoto** [magespecialist/m2-MSP_CmsImportExport#26]
https://github.com/magespecialist/m2-MSP_CmsImportExport/blob/3847872cebe1b0b7cfb62e7c216a04971a8f8678/Model/Content.php#L504

`main.CRITICAL: TypeError: array_intersect(): Argument #1 ($array) must be of type array, null given in /.../msp/cmsimportexport/Model/Content.php:504
`

a workaround could be to cast the arguments to array:

`$storesIntersect = array_intersect((array)$item->getStoreId(), (array)$storeIds);
`

**Comment by giacmir** [comment]
Hello @maxnoto,
would you mind opening a pull request for that?

**Comment by maxnoto** [comment]
Hello,
I just submitted the pull request.

Max

Il giorno lun 27 feb 2023 alle ore 08:42 Giacomo Mirabassi <
***@***.***> ha scritto:

**Comment by giacmir** [comment]
Thank you @maxnoto,
your pull request has been merged.
