### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by blizam** [magespecialist/m2-MSP_CmsImportExport#5]
Tried installing a Magento 2.1.5 ~ got the following error:

Using version ^0.1.4 for msp/cmsimportexport
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for msp/cmsimportexport ^0.1.4 -> satisfiable by msp/cmsimportexport[0.1.4].
    - Conclusion: remove magento/framework 100.1.5
    - Conclusion: don't install magento/framework 100.1.5
    - msp/cmsimportexport 0.1.4 requires magento/framework 100.0.* -> satisfiable by magento/framework[100.0.10, 1                                                              00.0.11, 100.0.12, 100.0.13, 100.0.14, 100.0.15, 100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 10                                                              0.0.9].
    - Can only install one of: magento/framework[100.1.5, 100.0.10].
    - Can only install one of: magento/framework[100.1.5, 100.0.11].
    - Can only install one of: magento/framework[100.1.5, 100.0.12].
    - Can only install one of: magento/framework[100.1.5, 100.0.13].
    - Can only install one of: magento/framework[100.1.5, 100.0.14].
    - Can only install one of: magento/framework[100.1.5, 100.0.15].
    - Can only install one of: magento/framework[100.1.5, 100.0.2].
    - Can only install one of: magento/framework[100.1.5, 100.0.3].
    - Can only install one of: magento/framework[100.1.5, 100.0.4].
    - Can only install one of: magento/framework[100.1.5, 100.0.5].
    - Can only install one of: magento/framework[100.1.5, 100.0.6].
    - Can only install one of: magento/framework[100.1.5, 100.0.7].
    - Can only install one of: magento/framework[100.1.5, 100.0.8].
    - Can only install one of: magento/framework[100.1.5, 100.0.9].
    - Installation request for magento/framework (locked at 100.1.5) -> satisfiable by magento/framework[100.1.5].

Installation failed, reverting ./composer.json to its original content.

**Comment by giacmir** [comment]
This extension is not currently compatible with Magento 2.1.*, that's why you have a dependency error.

**Comment by blizam** [comment]
Gotcha, ty for the reply... the versioning of 100.x through me for a loop... thought maybe it was only for Magento 1 though it said it was for M2... ty for clarifying
