### ISSUE TITLE
Magento 2.2 compatibility

### ISSUE THREAD

**Issue by ghost** [magespecialist/m2-MSP_CmsImportExport#7]
Hello,

Thank you for your work.

I have saved my cms page and block in previous version of Magento 2 (2.1.9).

Actually, i use the last version 2.2 of Magento.

How can i install this extension on Magento 2.2 ?

Actually Composer make an comatibility error.

Thank you in advance for you help.

I propose this in composer.json:

Just modify this line:

"magento/framework": "100.1.*", to "magento/framework": "100.2.*",

But i dont know if this solution is good.

**Comment by giacmir** [comment]
Hi @achatpc,

this extension has not been tested yet with 2.2. So I can't tell if changing version constraints is enough to guarantee its funcionality.

I can't give you an ETA for this, so feel free to test it yourself and open a pull request :-)

**Comment by giacmir** [comment]
@achatpc please keep this open since it's a confirmed defect.

**Comment by giuseppemorelli** [comment]
Hi guys,
I've tested the extension (import and export test) on magento 2.2.1.
Seems all correct.

How can manage 2.2.x and 2.1.x magento/framework dependency on composer?

2.2.x  => magento/framework 101.0.*
2.1.x  => magento/framework 100.1.*

```
 "require": {
        "php": "7.0.2|7.0.4|~7.0.6",
        "magento/framework": "<=101.0.*",
        "msp/common": "*",
        "magento/magento-composer-installer": "*"
    },
```

Can I open a pull request for that?

Thanks!

**Comment by daniloargentiero** [comment]
Fidex
