### ISSUE TITLE
Can't export blocks 

### ISSUE THREAD

**Issue by raivisdejus** [magespecialist/m2-MSP_CmsImportExport#9]
When I try to export blocks I get the error.
Page export works fine.

Magento ver. 2.1.7

> 
> 1 exception(s):
> Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /var/www/magento/vendor/msp/cmsimportexport/Model/Content.php on line 122
> 
> Exception #0 (Exception): Warning: Invalid argument supplied for foreach() in /var/www/magento/vendor/msp/cmsimportexport/Model/Content.php on line 122
> #0 /var/www/magento/vendor/msp/cmsimportexport/Model/Content.php(122): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', '/var/www/magent...', 122, Array)
> #1 /var/www/magento/vendor/msp/cmsimportexport/Model/Content.php(182): MSP\CmsImportExport\Model\Content->getStoreCodes(NULL)
> #2 /var/www/magento/vendor/msp/cmsimportexport/Model/Content.php(261): MSP\CmsImportExport\Model\Content->blockToArray(Object(Magento\Cms\Model\Block))
> #3 /var/www/magento/vendor/msp/cmsimportexport/Model/Content.php(303): MSP\CmsImportExport\Model\Content->blocksToArray(Array)
> #4 /var/www/magento/vendor/msp/cmsimportexport/Controller/Adminhtml/Block/MassExport.php(74): MSP\CmsImportExport\Model\Content->asZipFile(Array, Array)
> #5 /var/www/magento/var/generation/MSP/CmsImportExport/Controller/Adminhtml/Block/MassExport/Interceptor.php(24): MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport->execute()
> #6 /var/www/magento/vendor/magento/framework/App/Action/Action.php(102): MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport\Interceptor->execute()
> #7 /var/www/magento/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
> #8 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
> #9 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport\Interceptor->___callParent('dispatch', Array)
> #10 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('MSP\\CmsImportEx...', 'dispatch', Object(MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport\Interceptor), Array, 'adminAuthentica...')
> #11 /var/www/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #12 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #13 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('MSP\\CmsImportEx...', 'dispatch', Object(MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport\Interceptor), Array, 'adminMassaction...')
> #14 /var/www/magento/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #15 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #16 /var/www/magento/var/generation/MSP/CmsImportExport/Controller/Adminhtml/Block/MassExport/Interceptor.php(39): MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport\Interceptor->___callPlugins('dispatch', Array, Array)
> #17 /var/www/magento/vendor/magento/framework/App/FrontController.php(69): MSP\CmsImportExport\Controller\Adminhtml\Block\MassExport\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #18 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
> #19 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
> #20 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
> #21 /var/www/magento/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
> #22 /var/www/magento/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #23 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'buff_store_redi...')
> #24 /var/www/magento/app/code/Buff/StoreRedirect/Plugin/DoRedirect.php(92): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
> #25 /var/www/magento/vendor/magento/framework/Interception/Interceptor.php(142): Buff\StoreRedirect\Plugin\DoRedirect->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
> #26 /var/www/magento/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
> #27 /var/www/magento/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
> #28 /var/www/magento/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
> #29 /var/www/magento/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
> #30 {main}

**Comment by daniloargentiero** [comment]
Fixed in 1.1.0
